version: 0.2

environment:
  image: aws/codebuild/ruby:2.5.1

phases:
  install:
    commands:
      - bundle install
      - bundle install --deployment

  build:
    commands:
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml

artifacts:
  type: zip
  files:
    - template-export.yml

