AWSTemplateFormatVersion: '2010-09-09'
Description: send email daily from assignments posted on a public google calendar
Outputs:
  AssignmentsbotOutgoingMessageFunction:
    Description: Assignmentsbot Outgoing Message Function ARN
    Value:
      Fn::GetAtt:
      - AssignmentsbotOutgoingMessageFunction
      - Arn
  AssignmentsbotOutgoingMessageFunctionIamRole:
    Description: Implicit IAM Role created for Assignmentsbot Outgoing Message Function
      ARN
    Value:
      Fn::GetAtt:
      - AssignmentsbotOutgoingMessageFunctionRole
      - Arn
  PersonApi:
    Description: API Gateway endpoint URL for Prod stage for API Gateway Multi-Origin
      CORS function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
  PersonCreate:
    Description: API Gateway Multi-Origin CORS Lambda Function (Root) ARN
    Value:
      Fn::GetAtt:
      - AssignmentsbotCreatePersonFunction
      - Arn
Parameters:
  BucketName:
    AllowedPattern: ^[a-z0-9][a-z0-9-.]{1,61}[a-z0-9]$
    Default: assignmentsbot.com
    Description: The name for the bucket hosting your website
    Type: String
  EnvAPIKey:
    Default: assignmentsbotAPIKey
    Type: AWS::SSM::Parameter::Value<String>
  EnvGCal:
    Default: assignmentsbotCalendar
    Type: AWS::SSM::Parameter::Value<String>
  EnvMailgunAPIKey:
    Default: mailgunAPIKey
    Type: AWS::SSM::Parameter::Value<String>
  EnvMailgunDomain:
    Default: mailgunDomain
    Type: AWS::SSM::Parameter::Value<String>
Resources:
  AssignmentsbotCreatePersonFunction:
    Properties:
      CodeUri: s3://assignmentsbot-cloudformation/69bbe7acd1c4cbf9af683162838ee225
      Environment:
        Variables:
          DDB_PERSON_TABLE:
            Ref: PeopleDynamoDBTable
      Events:
        Options:
          Properties:
            Method: options
            Path: /people
          Type: Api
        Post:
          Properties:
            Method: post
            Path: /people
          Type: Api
      Handler: api/person_api.create
      MemorySize: 512
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: PeopleDynamoDBTable
      Runtime: ruby2.5
      Timeout: 60
    Type: AWS::Serverless::Function
  AssignmentsbotOutgoingMessageFunction:
    Properties:
      CodeUri: s3://assignmentsbot-cloudformation/69bbe7acd1c4cbf9af683162838ee225
      Environment:
        Variables:
          API_KEY:
            Ref: EnvAPIKey
          CALENDAR:
            Ref: EnvGCal
          DDB_PERSON_TABLE:
            Ref: PeopleDynamoDBTable
          DDB_TEAM_TABLE:
            Ref: TeamsDynamoDBTable
          MAILGUN_API_KEY:
            Ref: EnvMailgunAPIKey
          MAILGUN_DOMAIN:
            Ref: EnvMailgunDomain
      Events:
        Weekday4pmCron:
          Name: Weekday4pmESTCron
          Properties:
            Schedule: cron(0 21 ? * MON-FRI *)
          Type: Schedule
      Handler: app.lambda_handler
      MemorySize: 512
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: PeopleDynamoDBTable
      - DynamoDBCrudPolicy:
          TableName:
            Ref: TeamsDynamoDBTable
      Runtime: ruby2.5
      Timeout: 60
    Type: AWS::Serverless::Function
  PeopleDynamoDBTable:
    Properties:
      AttributeDefinitions:
      - AttributeName: email_address
        AttributeType: S
      - AttributeName: confirmation_token
        AttributeType: S
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
      - IndexName: confirmation_token_index
        KeySchema:
        - AttributeName: confirmation_token
          KeyType: HASH
        Projection:
          ProjectionType: ALL
      KeySchema:
      - AttributeName: email_address
        KeyType: HASH
      TableName: abPeopleTable-prod
    Type: AWS::DynamoDB::Table
  TeamsDynamoDBTable:
    Properties:
      AttributeDefinitions:
      - AttributeName: name
        AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
      - AttributeName: name
        KeyType: HASH
      TableName: abTeamsTable-prod
    Type: AWS::DynamoDB::Table
  WebsiteBucket:
    DeletionPolicy: Retain
    Properties:
      BucketName:
        Ref: BucketName
      VersioningConfiguration:
        Status: Enabled
      WebsiteConfiguration:
        ErrorDocument: index.html
        IndexDocument: index.html
    Type: AWS::S3::Bucket
  WebsiteBucketPolicy:
    Properties:
      Bucket:
        Ref: WebsiteBucket
      PolicyDocument:
        Statement:
        - Action: s3:GetObject
          Effect: Allow
          Principal: '*'
          Resource:
            Fn::Sub: arn:aws:s3:::${WebsiteBucket}/*
        Version: 2012-10-17
    Type: AWS::S3::BucketPolicy
Transform: AWS::Serverless-2016-10-31
