AWSTemplateFormatVersion: '2010-09-09'
Description: send email daily from assignments posted google calendar
Outputs:
  AssignmentsbotOutgoingMessageFunction:
    Description: Assignmentsbot Outgoing Message Function ARN
    Value:
      Fn::GetAtt:
      - AssignmentsbotOutgoingMessageFunction
      - Arn
  AssignmentsbotOutgoingMessageFunctionIamRole:
    Description: Implicit IAM Role created for Assignmentsbot Outgoing Message Function
      ARN
    Value:
      Fn::GetAtt:
      - AssignmentsbotOutgoingMessageFunctionRole
      - Arn
Parameters:
  EnvAPIKey:
    Default: assignmentsbotAPIKey
    Type: AWS::SSM::Parameter::Value<String>
  EnvGCal:
    Default: assignmentsbotCalendar
    Type: AWS::SSM::Parameter::Value<String>
Resources:
  AssignmentsbotOutgoingMessageFunction:
    Properties:
      CodeUri: s3://assignmentsbot-cloudformation/8e9e5c76c2087c2fd1ad622901a77ba5
      Environment:
        Variables:
          API_KEY:
            Ref: EnvAPIKey
          CALENDAR:
            Ref: EnvGCal
      Handler: app.lambda_handler
      Runtime: ruby2.5
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
