AWSTemplateFormatVersion: '2010-09-09'
Description: send email daily from assignments posted on a public google calendar
Outputs:
  AssignmentsbotOutgoingMessageFunction:
    Description: Assignmentsbot Outgoing Message Function ARN
    Value:
      Fn::GetAtt:
      - AssignmentsbotOutgoingMessageFunction
      - Arn
  AssignmentsbotOutgoingMessageFunctionIamRole:
    Description: Implicit IAM Role created for Assignmentsbot Outgoing Message Function
      ARN
    Value:
      Fn::GetAtt:
      - AssignmentsbotOutgoingMessageFunctionRole
      - Arn
Parameters:
  EnvAPIKey:
    Default: assignmentsbotAPIKey
    Type: AWS::SSM::Parameter::Value<String>
  EnvGCal:
    Default: assignmentsbotCalendar
    Type: AWS::SSM::Parameter::Value<String>
  EnvMailgunAPIKey:
    Default: mailgunAPIKey
    Type: AWS::SSM::Parameter::Value<String>
  EnvMailgunDomain:
    Default: mailgunDomain
    Type: AWS::SSM::Parameter::Value<String>
Resources:
  AssignmentsbotOutgoingMessageFunction:
    Properties:
      CodeUri: s3://assignmentsbot-cloudformation/c147f532a124853d48902bbd9057313c
      Environment:
        Variables:
          API_KEY:
            Ref: EnvAPIKey
          CALENDAR:
            Ref: EnvGCal
          DDB_PERSON_TABLE:
            Ref: PeopleDynamoDBTable
          DDB_TEAM_TABLE:
            Ref: TeamsDynamoDBTable
          MAILGUN_API_KEY:
            Ref: EnvMailgunAPIKey
          MAILGUN_DOMAIN:
            Ref: EnvMailgunDomain
      Events:
        Weekday4pmCron:
          Name: Weekday4pmESTCron
          Properties:
            Schedule: cron(0 21 ? * MON-FRI *)
          Type: Schedule
      Handler: app.lambda_handler
      MemorySize: 512
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: PeopleDynamoDBTable
      - DynamoDBCrudPolicy:
          TableName:
            Ref: TeamsDynamoDBTable
      Runtime: ruby2.5
      Timeout: 60
    Type: AWS::Serverless::Function
  PeopleDynamoDBTable:
    Properties:
      AttributeDefinitions:
      - AttributeName: email_address
        AttributeType: S
      - AttributeName: confirmation_token
        AttributeType: S
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
      - IndexName: confirmation_token_index
        KeySchema:
        - AttributeName: confirmation_token
          KeyType: HASH
        Projection:
          ProjectionType: ALL
      KeySchema:
      - AttributeName: email_address
        KeyType: HASH
      TableName: abPeopleTable-prod
    Type: AWS::DynamoDB::Table
  TeamsDynamoDBTable:
    Properties:
      AttributeDefinitions:
      - AttributeName: name
        AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
      - AttributeName: name
        KeyType: HASH
      TableName: abTeamsTable-prod
    Type: AWS::DynamoDB::Table
Transform: AWS::Serverless-2016-10-31
