AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'send email daily from assignments posted google calendar'

Parameters:
  EnvGCal:
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: assignmentsbotCalendar
  EnvAPIKey:
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: assignmentsbotAPIKey
  EnvMailgunAPIKey:
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: mailgunAPIKey
  EnvMailgunDomain:
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: mailgunDomain

Resources:
  AssignmentsbotOutgoingMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: ruby2.5
      CodeUri: ./
      Environment:
        Variables:
          CALENDAR: !Ref EnvGCal
          API_KEY: !Ref EnvAPIKey
          MAILGUN_API_KEY: !Ref EnvMailgunAPIKey
          MAILGUN_DOMAIN: !Ref EnvMailgunDomain

Outputs:
  AssignmentsbotOutgoingMessageFunction:
    Description: "Assignmentsbot Outgoing Message Function ARN"
    Value: !GetAtt AssignmentsbotOutgoingMessageFunction.Arn

  AssignmentsbotOutgoingMessageFunctionIamRole:
    Description: "Implicit IAM Role created for Assignmentsbot Outgoing Message Function ARN"
    Value: !GetAtt AssignmentsbotOutgoingMessageFunctionRole.Arn
